using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraRotation : MonoBehaviour {

    public float horizontalSpeed = 2.0f;
    public float verticalSpeed = 2.0f;
    float yaw;
    float pitch;

    public Transform playerCamera;

    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
    }


	// Update is called once per frame
	void Update ()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Cursor.lockState = CursorLockMode.Locked;
        }

        yaw += horizontalSpeed * Input.GetAxis("Mouse X");
        pitch -= verticalSpeed * Input.GetAxis("Mouse Y");

        
        playerCamera.eulerAngles = new Vector3 (pitch, yaw , 0);
    }
}
